// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_store.Models;

#nullable disable

namespace dotnet_store.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250527133506_AddSlider")]
    partial class AddSlider
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("dotnet_store.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Telefon",
                            Url = "telefon"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Elektronik",
                            Url = "Elektronik"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Beyaz Eşya",
                            Url = "beyaz-esya"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Giyim",
                            Url = "giyim"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Kozmetik",
                            Url = "kozmetik"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Saat",
                            Url = "saat"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Hoperlör",
                            Url = "Hoperlor"
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Kulaklık",
                            Url = "kulaklik"
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "Bileşen",
                            Url = "bilesen"
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "Hobi",
                            Url = "hobi"
                        });
                });

            modelBuilder.Entity("dotnet_store.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHome")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin faucibus a turpis ac porta. In feugiat eget arcu vel pulvinar. Nunc aliquam nisl a lacus semper, suscipit pharetra arcu elementum. Aenean commodo ipsum tortor, vel pellentesque eros hendrerit a. Morbi pulvinar vehicula urna, eu fringilla ipsum tincidunt at. Donec a sapien molestie, posuere libero nec, laoreet nisl. Duis pellentesque nunc eget dui viverra, pretium vehicula enim congue. Ut id quam eget arcu ullamcorper convallis nec ut ex. Duis auctor, lectus nec placerat bibendum, nibh purus rhoncus ex, id sollicitudin metus lectus aliquam ex. Donec et est et risus mattis vestibulum. Nulla sit amet mauris velit. Ut non lobortis ligula, non tincidunt ex. Suspendisse at ultricies nibh, sed interdum ipsum.",
                            Image = "1.jpeg",
                            IsActive = false,
                            IsHome = true,
                            Price = 10000.0,
                            ProductName = "Apple Watch 7"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin faucibus a turpis ac porta. In feugiat eget arcu vel pulvinar. Nunc aliquam nisl a lacus semper, suscipit pharetra arcu elementum. Aenean commodo ipsum tortor, vel pellentesque eros hendrerit a. Morbi pulvinar vehicula urna, eu fringilla ipsum tincidunt at. Donec a sapien molestie, posuere libero nec, laoreet nisl. Duis pellentesque nunc eget dui viverra, pretium vehicula enim congue. Ut id quam eget arcu ullamcorper convallis nec ut ex. Duis auctor, lectus nec placerat bibendum, nibh purus rhoncus ex, id sollicitudin metus lectus aliquam ex. Donec et est et risus mattis vestibulum. Nulla sit amet mauris velit. Ut non lobortis ligula, non tincidunt ex. Suspendisse at ultricies nibh, sed interdum ipsum.",
                            Image = "2.jpeg",
                            IsActive = true,
                            IsHome = true,
                            Price = 20000.0,
                            ProductName = "Apple Watch 8"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin faucibus a turpis ac porta. In feugiat eget arcu vel pulvinar. Nunc aliquam nisl a lacus semper, suscipit pharetra arcu elementum. Aenean commodo ipsum tortor, vel pellentesque eros hendrerit a. Morbi pulvinar vehicula urna, eu fringilla ipsum tincidunt at. Donec a sapien molestie, posuere libero nec, laoreet nisl. Duis pellentesque nunc eget dui viverra, pretium vehicula enim congue. Ut id quam eget arcu ullamcorper convallis nec ut ex. Duis auctor, lectus nec placerat bibendum, nibh purus rhoncus ex, id sollicitudin metus lectus aliquam ex. Donec et est et risus mattis vestibulum. Nulla sit amet mauris velit. Ut non lobortis ligula, non tincidunt ex. Suspendisse at ultricies nibh, sed interdum ipsum.",
                            Image = "3.jpeg",
                            IsActive = false,
                            IsHome = true,
                            Price = 30000.0,
                            ProductName = "Apple Watch 9"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin faucibus a turpis ac porta. In feugiat eget arcu vel pulvinar. Nunc aliquam nisl a lacus semper, suscipit pharetra arcu elementum. Aenean commodo ipsum tortor, vel pellentesque eros hendrerit a. Morbi pulvinar vehicula urna, eu fringilla ipsum tincidunt at. Donec a sapien molestie, posuere libero nec, laoreet nisl. Duis pellentesque nunc eget dui viverra, pretium vehicula enim congue. Ut id quam eget arcu ullamcorper convallis nec ut ex. Duis auctor, lectus nec placerat bibendum, nibh purus rhoncus ex, id sollicitudin metus lectus aliquam ex. Donec et est et risus mattis vestibulum. Nulla sit amet mauris velit. Ut non lobortis ligula, non tincidunt ex. Suspendisse at ultricies nibh, sed interdum ipsum.",
                            Image = "4.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 40000.0,
                            ProductName = "Apple Watch 10"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin faucibus a turpis ac porta. In feugiat eget arcu vel pulvinar. Nunc aliquam nisl a lacus semper, suscipit pharetra arcu elementum. Aenean commodo ipsum tortor, vel pellentesque eros hendrerit a. Morbi pulvinar vehicula urna, eu fringilla ipsum tincidunt at. Donec a sapien molestie, posuere libero nec, laoreet nisl. Duis pellentesque nunc eget dui viverra, pretium vehicula enim congue. Ut id quam eget arcu ullamcorper convallis nec ut ex. Duis auctor, lectus nec placerat bibendum, nibh purus rhoncus ex, id sollicitudin metus lectus aliquam ex. Donec et est et risus mattis vestibulum. Nulla sit amet mauris velit. Ut non lobortis ligula, non tincidunt ex. Suspendisse at ultricies nibh, sed interdum ipsum.",
                            Image = "5.jpeg",
                            IsActive = true,
                            IsHome = true,
                            Price = 50000.0,
                            ProductName = "Apple Watch 11"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin faucibus a turpis ac porta. In feugiat eget arcu vel pulvinar. Nunc aliquam nisl a lacus semper, suscipit pharetra arcu elementum. Aenean commodo ipsum tortor, vel pellentesque eros hendrerit a. Morbi pulvinar vehicula urna, eu fringilla ipsum tincidunt at. Donec a sapien molestie, posuere libero nec, laoreet nisl. Duis pellentesque nunc eget dui viverra, pretium vehicula enim congue. Ut id quam eget arcu ullamcorper convallis nec ut ex. Duis auctor, lectus nec placerat bibendum, nibh purus rhoncus ex, id sollicitudin metus lectus aliquam ex. Donec et est et risus mattis vestibulum. Nulla sit amet mauris velit. Ut non lobortis ligula, non tincidunt ex. Suspendisse at ultricies nibh, sed interdum ipsum.",
                            Image = "6.jpeg",
                            IsActive = false,
                            IsHome = false,
                            Price = 60000.0,
                            ProductName = "Apple Watch 12"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin faucibus a turpis ac porta. In feugiat eget arcu vel pulvinar. Nunc aliquam nisl a lacus semper, suscipit pharetra arcu elementum. Aenean commodo ipsum tortor, vel pellentesque eros hendrerit a. Morbi pulvinar vehicula urna, eu fringilla ipsum tincidunt at. Donec a sapien molestie, posuere libero nec, laoreet nisl. Duis pellentesque nunc eget dui viverra, pretium vehicula enim congue. Ut id quam eget arcu ullamcorper convallis nec ut ex. Duis auctor, lectus nec placerat bibendum, nibh purus rhoncus ex, id sollicitudin metus lectus aliquam ex. Donec et est et risus mattis vestibulum. Nulla sit amet mauris velit. Ut non lobortis ligula, non tincidunt ex. Suspendisse at ultricies nibh, sed interdum ipsum.",
                            Image = "7.jpeg",
                            IsActive = true,
                            IsHome = true,
                            Price = 70000.0,
                            ProductName = "Apple Watch 13"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin faucibus a turpis ac porta. In feugiat eget arcu vel pulvinar. Nunc aliquam nisl a lacus semper, suscipit pharetra arcu elementum. Aenean commodo ipsum tortor, vel pellentesque eros hendrerit a. Morbi pulvinar vehicula urna, eu fringilla ipsum tincidunt at. Donec a sapien molestie, posuere libero nec, laoreet nisl. Duis pellentesque nunc eget dui viverra, pretium vehicula enim congue. Ut id quam eget arcu ullamcorper convallis nec ut ex. Duis auctor, lectus nec placerat bibendum, nibh purus rhoncus ex, id sollicitudin metus lectus aliquam ex. Donec et est et risus mattis vestibulum. Nulla sit amet mauris velit. Ut non lobortis ligula, non tincidunt ex. Suspendisse at ultricies nibh, sed interdum ipsum.",
                            Image = "8.jpeg",
                            IsActive = false,
                            IsHome = false,
                            Price = 80000.0,
                            ProductName = "Apple Watch 14"
                        });
                });

            modelBuilder.Entity("dotnet_store.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Slider 1 Desc",
                            Image = "slider-1.jpeg",
                            Index = 0,
                            IsActive = true,
                            Title = "Slider 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Slider 2 Desc",
                            Image = "slider-2.jpeg",
                            Index = 1,
                            IsActive = true,
                            Title = "Slider 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Slider 3 Desc",
                            Image = "slider-3.jpeg",
                            Index = 2,
                            IsActive = true,
                            Title = "Slider 3"
                        });
                });

            modelBuilder.Entity("dotnet_store.Models.Product", b =>
                {
                    b.HasOne("dotnet_store.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("dotnet_store.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
